version: '3.8'

services:
  angular-app:
    build: .
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules  # Isso evita sobreposição da pasta node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  # Melhora o watch de arquivos no Docker
    networks:
      - angular-network

networks:
  angular-network:
    driver: bridge